# Generated by Django 4.0.7 on 2022-08-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationpage',
            name='address',
            field=models.TextField(blank=True, help_text='Address', null=True),
        ),
        migrations.AddField(
            model_name='organizationpage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organizationpage',
            name='site',
            field=models.URLField(blank=True, help_text='Site', null=True),
        ),
    ]
