# Generated by Django 4.0.7 on 2022-08-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organizationpage_address_organizationpage_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationpage',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='organizationpage',
            name='email',
            field=models.EmailField(blank=True, help_text='Email', max_length=254, null=True),
        ),
    ]
